import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../supabase';

const TripContext = createContext();

export function useTrip() {
    return useContext(TripContext);
}

export function TripProvider({ children }) {
    // Check if Supabase is configured
    const isSupabaseConfigured = import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY;

    const [tripInfo, setTripInfo] = useState(() => {
        const saved = localStorage.getItem('trip_info');
        return saved ? JSON.parse(saved) : { name: 'Trip #1', id: 'demo' };
    });

    const [expenses, setExpenses] = useState([]);
    const [members, setMembers] = useState(['You', 'Sarah', 'Mike', 'John']);
    const [totalBudget, setTotalBudget] = useState(0);

    // Initial Load Logic (Local vs Cloud)
    useEffect(() => {
        if (!isSupabaseConfigured) {
            // Load from LocalStorage if no Supabase
            const savedExpenses = localStorage.getItem('trip_expenses');
            if (savedExpenses) setExpenses(JSON.parse(savedExpenses));

            const savedMembers = localStorage.getItem('trip_members');
            if (savedMembers) setMembers(JSON.parse(savedMembers));

            const savedBudget = localStorage.getItem('trip_budget');
            if (savedBudget) setTotalBudget(parseFloat(savedBudget));
            return;
        }

        // --- Supabase Logic ---
        const fetchTripData = async () => {
            if (!tripInfo.id || tripInfo.id === 'demo') return;

            // 1. Fetch Trip Details (Budget, etc)
            const { data: tripData, error: tripError } = await supabase
                .from('trips')
                .select('*')
                .eq('id', tripInfo.id)
                .single();

            if (tripData) {
                setTotalBudget(tripData.budget || 0);
            } else if (!tripError) {
                // Create trip if not exists
                await supabase.from('trips').insert([{ id: tripInfo.id, budget: 0, name: 'Trip' }]);
            }

            // 2. Fetch Expenses
            const { data: expenseData } = await supabase
                .from('expenses')
                .select('*')
                .eq('trip_id', tripInfo.id)
                .order('created_at', { ascending: false });

            if (expenseData) setExpenses(expenseData);
        };

        fetchTripData();

        // Real-time Subscription
        const channel = supabase
            .channel('trip_updates')
            .on('postgres_changes', { event: '*', schema: 'public', table: 'expenses', filter: `trip_id=eq.${tripInfo.id}` }, (payload) => {
                if (payload.eventType === 'INSERT') {
                    setExpenses(prev => [payload.new, ...prev]);
                }
            })
            .on('postgres_changes', { event: '*', schema: 'public', table: 'trips', filter: `id=eq.${tripInfo.id}` }, (payload) => {
                if (payload.new && payload.new.budget !== undefined) {
                    setTotalBudget(payload.new.budget);
                }
            })
            .subscribe();

        return () => {
            supabase.removeChannel(channel);
        };
    }, [isSupabaseConfigured, tripInfo.id]);


    // Local Storage Backup (Optional, but good for offline-first feel)
    useEffect(() => {
        if (!isSupabaseConfigured) {
            localStorage.setItem('trip_expenses', JSON.stringify(expenses));
            localStorage.setItem('trip_members', JSON.stringify(members));
            localStorage.setItem('trip_budget', totalBudget.toString());
        }
        localStorage.setItem('trip_info', JSON.stringify(tripInfo));
    }, [expenses, members, tripInfo, totalBudget, isSupabaseConfigured]);


    const addExpense = async (expense) => {
        const newExpense = {
            ...expense,
            trip_id: tripInfo.id,
            // id: generated by DB or local
        };

        if (isSupabaseConfigured) {
            // Optimistic UI update
            const tempId = Date.now().toString();
            setExpenses(prev => [{ ...newExpense, id: tempId, created_at: new Date().toISOString() }, ...prev]);

            const { error } = await supabase.from('expenses').insert([newExpense]);
            if (error) {
                console.error('Error adding expense:', error);
                // Revert optimistic update if needed? For now simple.
            } else {
                // The subscription will handle the update, but we might want to dedupe. 
                // Actually, subscription adds "new", so we might get a duplicate if we added it optimistically.
                // Better strategy for simple app: Don't optimistic update, OR filter out temp IDs when real one arrives.
                // For now, let's just wait for subscription (it's fast) or just fetch.
                // But for smoothness, let's keep it simple:
                // Update: Remove manual setExpenses here if subscription is ON, otherwise you get double.
                // But subscription is async.
                // Let's rely on subscription for incoming, but for local feel we want instant.
                // Fix: Don't setExpenses here if Supabase is on. The subscription handles it.
            }
        } else {
            // Local Mode
            setExpenses(prev => [{ ...newExpense, id: Date.now().toString(), date: new Date().toLocaleDateString() }, ...prev]);
        }
    };

    // Wrapper to update budget locally or in cloud
    const updateBudget = async (amount) => {
        setTotalBudget(amount);
        if (isSupabaseConfigured && tripInfo.id) {
            await supabase.from('trips').upsert({ id: tripInfo.id, budget: amount });
        }
    };

    const addMember = (name) => {
        if (!members.includes(name)) {
            setMembers(prev => [...prev, name]);
        }
    };

    const getSettlements = () => {
        // Basic algorithm: 
        // 1. Calculate net balance for each person
        // 2. Match debtors to creditors

        let balances = {};
        members.forEach(m => balances[m] = 0);

        expenses.forEach(exp => {
            const payer = exp.paidBy;
            const amount = parseFloat(exp.amount);
            const splitEqually = amount / members.length;

            // Payer gets +amount (they paid)
            balances[payer] = (balances[payer] || 0) + amount;

            // Everyone (including payer) "spins" splitEqually
            // So net: Payer paid 'amount', but consumed 'splitEqually'. Net change: +amount - splitEqually
            // Others: Paid 0, consumed 'splitEqually'. Net change: -splitEqually

            members.forEach(member => {
                balances[member] -= splitEqually;
            });
        });

        // Separate into owe and receive
        let debtors = [];
        let creditors = [];

        Object.entries(balances).forEach(([name, amount]) => {
            if (amount < -0.01) debtors.push({ name, amount }); // Negative means you owe
            if (amount > 0.01) creditors.push({ name, amount }); // Positive means you are owed
        });

        debtors.sort((a, b) => a.amount - b.amount);
        creditors.sort((a, b) => b.amount - a.amount);

        let settlements = [];
        let i = 0; // debtor index
        let j = 0; // creditor index

        while (i < debtors.length && j < creditors.length) {
            let debtor = debtors[i];
            let creditor = creditors[j];

            let amountOwed = Math.abs(debtor.amount);
            let amountToReceive = creditor.amount;

            let settlementAmount = Math.min(amountOwed, amountToReceive);

            settlements.push({
                from: debtor.name,
                to: creditor.name,
                amount: settlementAmount
            });

            debtor.amount += settlementAmount;
            creditor.amount -= settlementAmount;

            if (Math.abs(debtor.amount) < 0.01) i++;
            if (creditor.amount < 0.01) j++;
        }

        return settlements;
    };

    const totals = {
        totalSpend: expenses.reduce((acc, curr) => acc + parseFloat(curr.amount), 0),
        userShare: 0 // To be calculated or specialized
    };

    return (
        <TripContext.Provider value={{
            expenses,
            members,
            tripInfo,
            setTripInfo,
            totalBudget,
            setTotalBudget: updateBudget,
            addExpense,
            addMember,
            getSettlements,
            totals
        }}>
            {children}
        </TripContext.Provider>
    );
}
